[package]
name = "core"
version = "0.0.1"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2018"

[dependencies]
utils = { path = "../utils" }

rand = "0.7.3"
log = "0.4.11"

[dependencies.clap]
version = "4.3.0"
features = ["cargo", "derive"]
