[package]
name = "core"
version = "0.0.1"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2018"

[dependencies]
utils = { path = "../utils" }
tracing = "0.1.37"

[dependencies.clap]
version = "4.3.0"
features = ["cargo", "derive"]
